// <auto-generated />
using System;
using LoanBee.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanBee.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoanBee.Models.Entities.Application", b =>
                {
                    b.Property<Guid>("Application_no")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Application_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Application_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Loan_amount")
                        .HasColumnType("int");

                    b.Property<string>("Loan_purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loan_tenor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Application_no");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("LoanBee.Models.Entities.BankAccount", b =>
                {
                    b.Property<string>("Account_no")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Account_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relationship_since")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Account_no");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("LoanBee.Models.Entities.Business", b =>
                {
                    b.Property<string>("Business_tin_no")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Business_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Business_landline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Business_mobile_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Business_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Business_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Business_website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Office_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Office_zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Business_tin_no");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("LoanBee.Models.Entities.Owner", b =>
                {
                    b.Property<string>("Owner_tin_no")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Owner_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Owner_birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Owner_citizenship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner_civil_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner_education")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner_email_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner_gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner_landline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner_mobile_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner_place_of_birth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Owner_tin_no");

                    b.ToTable("Owners");
                });
#pragma warning restore 612, 618
        }
    }
}
